# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Code formatting

on:
  workflow_call:

jobs:
  Black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Specify all python versions you might want to perform the actions on
        python-version: [ "3.11" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black 
          pip install isort
      - name: Run isort, docformatter and black checks
        id: checks
        continue-on-error: true
        run: |
          isort . --check
          black . --check
      - name: Run isort and black when required and commit back
        if: ${{ failure() || steps.checks.outcome == 'failure'}}
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PYELQ_TOKEN }}
        run: |
          isort .
          black .
          git config --global user.name 'code_reformat'
          git config --global user.email ''
          git remote set-url origin "https://$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_REPOSITORY"
          git fetch
          git checkout ${{ github.head_ref }}
          git commit --signoff -am "Automatic reformat of code"
          git push
