# SPDX-FileCopyrightText: 2026 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: ManualPublishDocs

permissions: write-all

on:
  workflow_dispatch:

jobs:
  PublishDocs:
    uses: sede-open/pyELQ/.github/workflows/publish_docs.yml@main
