# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: ManualPublishDocs

on:
  workflow_dispatch:

jobs:
  PublishDocs:
    uses: sede-open/pyELQ/.github/workflows/publish_docs.yml@main
    needs: Build
