# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

on:
  - push

name: Pylint Check
jobs:
  Pylint:
    # Specify the operating system GitHub has to use to perform the checks (ubuntu seems to be default)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Specify all python versions you might want to perform the actions on
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install .
    - name: Analysing the code with pylint
    # Run through the src/pyelq/ directory and check all .py files with pylint
      run: |
        python -m pylint `find -regextype egrep -regex '(.*src/pyelq/.*.py)$'` --output-format=parseable:pylint_report.out
    - name: Upload pylint results
      uses: actions/upload-artifact@v3
      with:
        name: pylint_report
        path: pylint_report.out
      if: ${{ always() }}